---
title: "Analisis de germinación en _Pisum sativum_"
author: "Acuña Ramirez Edinson Pooll,
         Grandes Castro Brayan Eliseo,
         Llaja Zuta Erika,
         Mondragón Herrera Edwin,
         Santillan Puerta Jaime Alexander,
         Rojas Campos Griselida"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    embed-resources: true
    output-file: index
editor_options: 
  chunk_output_type: console
---
# Introducción

# Materiales y Métodos

## Selección e instalacion del material vegetal
Las semillas de _Pisum sativum_ fueron adquiridas en el mercado central de la ciudad de Chachapoyas. Posteriormente, se seleccionaron las semillas más vigorosas y se distribuyeron 25 semillas en cada uno de los 12 tapers, sumando un total de 300 semillas para evaluar la respuesta de las semillas en condiciones de luz y oscuridad a temperatura ambiente. Para medir los índices de germinación en los tapers, se colocó papel toalla en su interior, y aquellos que se iban a mantener en oscuridad fueron cubiertos con papel aluminio. 

## Elaboracion de etiquetas
Se utilizó el paquete GerminaR (Flavio-Lozano et al., 2019) para realizar etiquetas en R y analizar los principales índices de germinación, las etiquetas se eleboraron de acuerdo al siguiente código

```{r}
source("https://inkaverse.com/setup.r")

url <- "https://docs.google.com/spreadsheets/d/1Vanuog99Wi1GnLu-DiweamnZG4APoaVjLrcXqSb049g/edit?gid=1547504271#gid=1547504271"

gs <- url %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read(ss = .,sheet = "fb")

library(huito)

font <- c("Purple Purse", "Tillana", "Courgette")

huito_fonts(font)
va <- 1.2
label <- fb %>% 
  mutate(color = case_when(
    factor1 %in% "sin_luz" ~ "black"
    , factor1 %in% "con_luz" ~ "black"
  )) %>% 
  label_layout(size = c(5, 3)
               , border_color = "blue"
  ) %>%
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(5, 1)
    , position = c(2.5, 0.5)
  ) %>%
  include_image(value = "https://www.untrm.edu.pe/assets/images/untrmazul.png"
                , size = c(2.4,1.6)
                , position = c(1.4, 2.6)
  ) %>% 
  include_image(
    value = "https://i.postimg.cc/2jGKcGpz/guisante-1.png"
    , size = c(2.5, 1.3)
    , position = c(3.3, 2.5)
  ) %>%
  include_image(
    value = "https://i.postimg.cc/MK6c1fNB/grupo4-octagono.png"
    , size = c(2, 0.8)
    , position = c(4.45,2.5)
  ) %>%

  include_barcode(
    value = "qrcode"
    , size = c(1, 1)
    , position = c(4.45, 1.58)
  ) %>%

  include_text(value = "Pisum sativum"
               , position = c(1.98, 2.08)
               , size = 9.5
               , color = "black"
               , font[3]
  ) %>%
  include_text(value = "Orden: Fabales"
               , position = c(1.3,1.68)
               , size = 8.5
               , color = "black"
               , font[1]
  ) %>%
  include_text(value = "Familia: Fabaceae"
               , position = c(1.5, 1.28)
               , size = 8.5
               , color = "black"
               , font[1]
  ) %>%
  include_text(value = "factor1"
               , position = c(3.3, 1.68)
               , size = 10
               , color = "color" # dynamic column
               , font[2]
  ) %>% 
  include_text(value = "plots"
               , position = c(3.4, 1.28)
               , angle = 0
               , size = 10
               , color = "black"
               , font[3]
  ) 
label %>% label_print()
 # label %>%
#   label_print(mode = "complete", filename = "etiquetas1", nlabels = 12)
# 
```
## Diseño experimental
Se empleo un Diseño Completamente al Azar (DCA) con dos tratamientos (sin luz y con luz) cada tratamiento contó con 6 repeticiones y 25 unidades experimentales.

# Resultados

## Semillas germinadas (grs)

## Tiempo medio de germinabilidad (mgt)

## velocidad de germinación (gsp)

## Variación de la germinación (vgt)
